---
title: "Homework 4"
output: html_document
date: "2023-10-03"
---
# Import the dataset and Install the package
```{r}
library(readxl)
ImportationDataofChina <- read_excel("C:/Users/xinxf/OneDrive/Desktop/Rutgers-NB 2023 Fall/Business Forecasting/ImportationDataofChina.xlsx")
View(ImportationDataofChina)

library(fpp)
library(fpp2)
library(TTR)
```
# Create Times Series
```{r}
IPV_ts<-ts(ImportationDataofChina$`Periodic Imporation Value`, frequency = 12,start = c(2018,9),end = c(2023,8))
IPV_ts
attributes(IPV_ts)
plot(IPV_ts)
```
#take Mean of all available history
```{r}
mean_forecast <- meanf(IPV_ts,6)
plot(mean_forecast)
```
#Naive
```{r}
naive_forecast <- naive(IPV_ts,6)
plot(naive_forecast)
```
# Random Walk (add noise) drift model
```{r}
rwf_forecast <- rwf(IPV_ts,6)
rwf_forecast <- rwf(IPV_ts,6, drift=TRUE)
plot(rwf_forecast)


```
# Seasonal Value
```{r}
snaive_forecast <- snaive(IPV_ts,6)
```
#plot all of these together
```{r}
plot(mean_forecast)
lines(naive_forecast$mean,col="red")
lines(rwf_forecast$mean,col="green")
lines(snaive_forecast$mean,col="black")
```
#Drift
```{r}
rwf_forecast <- rwf(IPV_ts,6, drift=TRUE)
plot(mean_forecast)
lines(naive_forecast$mean,col="red")
lines(snaive_forecast$mean,col="black")
lines(rwf_forecast$mean,col="green")

```
# Moving average
```{r}
plot(mean_forecast)
MA5_forecast <- ma(IPV_ts,order=5)
lines(MA5_forecast,col="pink")
MA9_forecast <- ma(IPV_ts,order=9)
lines(MA9_forecast,col="blue")
# For moving average method, we choose two orders. Order 5 focuses more on the recent data of that period so it's more responsive. Order 9 focuses more on historical data so it's more smoothing than Order 5.
```
# Holtwinter
```{r}
HoltWinters(IPV_ts,beta=FALSE,gamma=FALSE)
SSE_Simple <- HoltWinters(IPV_ts,beta=FALSE,gamma=FALSE)
attributes(SSE_Simple)
plot(SSE_Simple)
SSE_Simple$SSE
SSE_Simple$fitted
# alpha=0.415. As a result, the ets we got focused more on old data. So the model will be: Fi+1=Di*0.4150249+(1-0.4150249)*Fi
```
# SSE plus Trend
```{r}
SSE_Trend <- HoltWinters(IPV_ts,gamma=FALSE)
plot(SSE_Trend)
SSE_Trend
attributes(SSE_Trend)
SSE_Trend$SSE
#
```
# SSE plus Trend and Seasonality
```{r}
SSE_Winters <- HoltWinters(IPV_ts)
SSE_Winters$SSE
plot(SSE_Winters)
```
#ETS
```{r}
ets(IPV_ts)
ets_forecast <- ets(IPV_ts)
attributes(ets)
attributes(ets_forecast)
ets_forecast$mse
```
#Forecast
```{r}
forecast.ets(ets_forecast, h=6)
forecast_ets <- forecast.ets(ets_forecast, h=6)
forecast_MA5 <- forecast(MA5_forecast,h=6)
forecast_MA9 <- forecast(MA9_forecast,h=6)
plot(forecast_ets)
lines(MA5_forecast,col="pink")
lines(MA9_forecast,col="blue")

```
#Confidence Interval
```{r}
print(forecast_ets) # confidence interval of ETS model
print(rwf_forecast) # confidence interval of random walk model
print(naive_forecast) # confidence interval of naive model
print(snaive_forecast) # confidence interval of seasonal naive model
print(forecast_MA5) # confidence interval of Moving average with order 5
print(forecast_MA9) # confidence interval of Moving average with order 9
```

# Compare
```{r}
accuracy(forecast_ets)
accuracy(rwf_forecast)
accuracy(naive_forecast)
accuracy(snaive_forecast)
accuracy(forecast_MA5)
accuracy(forecast_MA9)
# As a result, we choose MA9 method because it has the lowest MAE.
```




